name: Bug fix
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: 🪲 Bug Overview
      description: Please provide a description of the bug that was occurring.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🤔 How to Resolve Bugs
      description: By what means did you resolve the bug?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Below are the options. Please fill them out if you would like.
  - type: textarea
    attributes:
      label: 📂 Details of Changes
      description: Please include a brief description of each file you have made changes to.
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🐙 Related Issues
      description: Enter the relevant issue in github with "#number".
    validations:
      required: false
  - type: textarea
    attributes:
      label: 💬 Others
    validations:
      required: false
