name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: ⭐ Overview
      description: A description of what the bug is
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Below are the options. Please fill them out if you would like.
  - type: textarea
    attributes:
      label: 🪜 Reproduction procedures
      description: Steps to reproduce the behavior
      value: |
        1.
        2.
        3.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ❗ Expected behavior
      description: A description of what you expected to happen
    validations:
      required: false
  - type: dropdown
    attributes:
      label: 🧭 What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
  - type: textarea
    attributes:
      label: 📝 Relevant log output
      description: Copy and paste the relevant log output.
      render: shell
  - type: textarea
    id: other
    attributes:
      label: 💬 Other
