name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for using it! Let me know your request!
  - type: textarea
    id: main
    attributes:
      label: Request
      description: What additional or enhanced features would you like to see?
      placeholder: Please describe clearly and concisely.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Below are the options. Please fill them out if you would like.
  - type: textarea
    id: background
    attributes:
      label: Request Background
      description: What background did you feel necessitated the above?
      placeholder: Please describe clearly and concisely.
    validations:
      required: false
