---
name: Feature request
description: Suggest an idea for this project
title: "[FEATURE]: "
labels: ["enhancement"]
---
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Overview
      description: What features would you like to see added?
      placeholder: Please describe clearly and concisely.
    validations:
      required: true
